### ISSUE TITLE
アカウント情報を返すAPIの新設

### ISSUE THREAD

**Issue by pasta04** [RTAinJapan/rtainjapan-twitter-api-node#3]
現状ではクライアントから投稿したツイートの情報しか返せなくなっている。
これだとDBにデータが無い時に、今どのアカウントとして動いているのかが傍目からわからない。

- リクエスト
  - GET /me
- レスポンス
  - {"screen_name": "rtainjapan"}

みたいなのを用意して、今何のアカウントで動いてるのかわかるようにしたい。
この情報はtwitter apiで取得するような正確なものでなくてよくて、例えばenvに定義した情報をそのまま返すとかでもよい。

**Comment by cma2819** [comment]
`GET /me` で、`username` を返すようにしました

```json
{
  "username": "dev_cma"
}
```
